name: flcore
description: 'Flutter Utility tools package.'
version: 0.0.3

repository: 'https://github.com/Yhaourt/flcore'

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.2.1
  logger: ^2.4.0
  dio: ^5.5.0+1
  go_router: ^14.2.1
  get_it: ^7.7.0
  flutter_secure_storage: ^9.2.2
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  http: ^1.2.2
  rxdart: ^0.28.0
